### ISSUE TITLE
NAVBAR USER - Default Profile Picture

### ISSUE THREAD

**Issue by ergegananputra** [hanabi1a/PAD1_MuhammadiyahWebContentCollaboration#73]
![image](https://github.com/hanabi1a/PAD1_MuhammadiyahWebContentCollaboration/assets/126530940/babcd43c-3b28-4a83-94b1-12e39b8fc981)

## Deskripsi
Default Profile Picture Belum muncul

## TODO
membenarkan profile picture pada navbar

**Comment by hamza-malik003** [comment]
@ergegananputra Please assign me this task

**Comment by ergegananputra** [comment]
Okay, good luck @hamza-malik003
